// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcSSl3a9Je-5oK6bG43By-Ai1jgiChutQ',
    appId: '1:773750850161:web:08f365a0f95f7180be51d0',
    messagingSenderId: '773750850161',
    projectId: 'fir-profiles-ba8c9',
    authDomain: 'fir-profiles-ba8c9.firebaseapp.com',
    storageBucket: 'fir-profiles-ba8c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-E6zS4lLG2tiax3WM1MsS8nq-Y6sOIxw',
    appId: '1:773750850161:android:8fa0ca9c77f310f4be51d0',
    messagingSenderId: '773750850161',
    projectId: 'fir-profiles-ba8c9',
    storageBucket: 'fir-profiles-ba8c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLa3d5l4fSXd7V9VWj-RGlnJZahP4vuY',
    appId: '1:773750850161:ios:840bc11f8a7aa51dbe51d0',
    messagingSenderId: '773750850161',
    projectId: 'fir-profiles-ba8c9',
    storageBucket: 'fir-profiles-ba8c9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseuser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuLa3d5l4fSXd7V9VWj-RGlnJZahP4vuY',
    appId: '1:773750850161:ios:840bc11f8a7aa51dbe51d0',
    messagingSenderId: '773750850161',
    projectId: 'fir-profiles-ba8c9',
    storageBucket: 'fir-profiles-ba8c9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseuser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcSSl3a9Je-5oK6bG43By-Ai1jgiChutQ',
    appId: '1:773750850161:web:cc6fe3b39f279d9bbe51d0',
    messagingSenderId: '773750850161',
    projectId: 'fir-profiles-ba8c9',
    authDomain: 'fir-profiles-ba8c9.firebaseapp.com',
    storageBucket: 'fir-profiles-ba8c9.firebasestorage.app',
  );
}
